//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace betzazz1._1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class shakebEntities2 : DbContext
    {
        public shakebEntities2()
            : base("name=shakebEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_s_Reg_Result> sp_s_Reg()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_s_Reg_Result>("sp_s_Reg");
        }
    }
}
